name: Quality Assurance
on: [ pull_request, workflow_call ]
jobs:
  # IntelliJ formatter is f*#$ed...
  # format:
  #   name: QA IntelliJ Format
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v3
  #       with:
  #         distribution: temurin
  #         java-version: 17
  #     - uses: telenornorway/setup-intellij@v0
  #     - uses: telenornorway/action-intellij-format@v0
  lint:
    name: QA IntelliJ Lint
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: telenornorway/setup-intellij@v0
      - uses: telenornorway/action-intellij-inspect@v0
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew test
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: read
    uses: ./.github/workflows/codeql.yml
